<NameTagWidget>:
    size: 150, 50 
	canvas.before:
        PushMatrix
        Rotate:
            angle: root.angle
            origin: self.center
        
    canvas:
		#Color:
		#	rgb: 1, 1, 1
		#Rectangle:
		#	pos:self.pos
		#	size:self.size
			
		Color:
			rgba: self.color
        Rectangle:
            pos: self.pos
            size: self.size  
			
	canvas.after:
        PopMatrix
		
	Label:
		center: self.parent.center
		id:my_name_label
		text: 'User' + root.user