#:kivy 1.6.0
#:import kivy kivy

# -----------------------------------------------------------------------------------------

<PosterKeyboard>:
    ignore_dwell: True
    ignore_double_tap: True
    ignore_momentum: False

    do_collide_after_children: True

    margin_hint: .07, .05, .05, .05
    text_color: 1,1,1,0.8

    layout: "qwerty_full"

# -----------------------------------------------------------------------------------------
